version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pytest --cov=. -v -s --cov-fail-under=75
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 448049786285.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t python_app .
      - docker tag python_app:latest 448049786285.dkr.ecr.us-east-1.amazonaws.com/python_app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 448049786285.dkr.ecr.us-east-1.amazonaws.com/python_app:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-app-python","imageUri":"448049786285.dkr.ecr.us-east-1.amazonaws.com/python_app:latest"}]' > imageDefinitions.json
      - printf '{"ImageURI":"448049786285.dkr.ecr.us-east-1.amazonaws.com/python_app:latest"}' > imageDetail.json
      - cat imageDefinitions.json 
artifacts:
  files:
    - '**/*'
    - imageDefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json